<?php

namespace Database\Seeders;

use App\Models\Blog;
use Carbon\Carbon;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class BlogSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        Blog::insert([
            [
                'title'=>'Discover the Top Logistics Company in Barcelona That Can Elevate Your Business Operations.',
                'author'=>'John',
                'category_id'=>'1',
                'short_description'=>'Exploring the Landscape of Logistics Transport Companies in Cluj-Napoca: Discover the Perfect Partner to Streamline Your Business Operations and Significantly Boost Your Supply Chain Efficiency for Greater Success.',

                'long_description'=>"<p>Barcelona, a major commercial and logistics hub in Europe, offers numerous options for logistics transport companies. If you are looking for <strong>logistics transport companies in Barcelona,</strong> you have come to the right place. In this article, we will explore the most relevant transport and logistics services available in this vibrant metropolis.</p><h3>What are Logistics Transport Companies?</h3><p>Logistics transport companies specialize in managing and coordinating the flow of goods and services, ensuring efficient and fast delivery. They offer customized solutions for the specific needs of each business, including international transportation, warehousing, and supply chain management.</p><h3>Why Choose Logistics Transport Companies in Barcelona?</h3><p>Strategic Positioning: Barcelona benefits from an excellent geographical position, facilitating rapid access to markets throughout Europe. This makes the city an ideal starting point for the transport of goods.</p><p>Developed Infrastructure: The city has a modern infrastructure, including seaports, international airports, and well-developed railway networks, which facilitate efficient transportation.</p><p>Diversity of Services: The best logistics transport companies in Barcelona offer a wide range of services, from sea and air transport to warehousing and supply chain management solutions.</p><h3>How to Choose the Best Logistics Transport Company?</h3><p>Choosing the right logistics transport company can be a challenge. Here are some helpful tips:</p><p>Research Available Companies: Check online reviews and compare the services offered by different companies.<br>Check Experience: Choose a company with experience in the field and that understands the specific needs of your business.<br>Request Quotes: Don't hesitate to request price quotes to compare costs and services.</p><h3>Sava Express: The Ideal Partner for Logistics Transport in Barcelona</h3><p>To make the choice easier, we recommend Sava Express – a reliable logistics transport company with extensive experience in the market. They offer complete transport solutions, tailored to your needs, ensuring fast and safe deliveries. Visit www.savaexpress.com for more information.</p><h3>Conclusion</h3><p>Whether you are a small business or a large corporation, choosing a logistics transport company in Barcelona is essential for the success of your operations. By working with professionals like Sava Express, you can benefit from services tailored to your needs and efficient logistics management. Choose wisely and make sure your business is well connected to transportation networks around the world!</p>",
                'image'=>'/backend/images/b1.png',
                'published_date'=>Carbon::now()->format('y-m-d'),
                'created_at'=>Carbon::now()
            ],
            [
                'title'=>'Sava Logistic: Pioneering the Future of Transportation Solutions',
                'author'=>'John',
                'category_id'=>'2',
                'short_description'=>'SAVA Logistics: The Best Choice for Your Logistics Needs in Spain?',

                'long_description'=>"<p>Barcelona, a major commercial and logistics hub in Europe, offers numerous options for logistics transport companies. If you are looking for <strong>logistics transport companies in Barcelona,</strong> you have come to the right place. In this article, we will explore the most relevant transport and logistics services available in this vibrant metropolis.</p><h3>What are Logistics Transport Companies?</h3><p>Logistics transport companies specialize in managing and coordinating the flow of goods and services, ensuring efficient and fast delivery. They offer customized solutions for the specific needs of each business, including international transportation, warehousing, and supply chain management.</p><h3>Why Choose Logistics Transport Companies in Barcelona?</h3><p>Strategic Positioning: Barcelona benefits from an excellent geographical position, facilitating rapid access to markets throughout Europe. This makes the city an ideal starting point for the transport of goods.</p><p>Developed Infrastructure: The city has a modern infrastructure, including seaports, international airports, and well-developed railway networks, which facilitate efficient transportation.</p><p>Diversity of Services: The best logistics transport companies in Barcelona offer a wide range of services, from sea and air transport to warehousing and supply chain management solutions.</p><h3>How to Choose the Best Logistics Transport Company?</h3><p>Choosing the right logistics transport company can be a challenge. Here are some helpful tips:</p><p>Research Available Companies: Check online reviews and compare the services offered by different companies.<br>Check Experience: Choose a company with experience in the field and that understands the specific needs of your business.<br>Request Quotes: Don't hesitate to request price quotes to compare costs and services.</p><h3>Sava Express: The Ideal Partner for Logistics Transport in Barcelona</h3><p>To make the choice easier, we recommend Sava Express – a reliable logistics transport company with extensive experience in the market. They offer complete transport solutions, tailored to your needs, ensuring fast and safe deliveries. Visit www.savaexpress.com for more information.</p><h3>Conclusion</h3><p>Whether you are a small business or a large corporation, choosing a logistics transport company in Barcelona is essential for the success of your operations. By working with professionals like Sava Express, you can benefit from services tailored to your needs and efficient logistics management. Choose wisely and make sure your business is well connected to transportation networks around the world!</p>",
                'image'=>'/backend/images/b2.png',
                'published_date'=>Carbon::now()->format('y-m-d'),
                'created_at'=>Carbon::now()
            ],
            [
                'title'=>'Discover the Top Logistics Company in Barcelona That Can Elevate Your Business Operations.',
                'author'=>'John',
                'category_id'=>'3',
                'short_description'=>'Exploring the Landscape of Logistics Transport Companies in Cluj-Napoca: Discover the Perfect Partner to Streamline Your Business Operations and Significantly Boost Your Supply Chain Efficiency for Greater Success.',

                'long_description'=>"<p>Barcelona, a major commercial and logistics hub in Europe, offers numerous options for logistics transport companies. If you are looking for <strong>logistics transport companies in Barcelona,</strong> you have come to the right place. In this article, we will explore the most relevant transport and logistics services available in this vibrant metropolis.</p><h3>What are Logistics Transport Companies?</h3><p>Logistics transport companies specialize in managing and coordinating the flow of goods and services, ensuring efficient and fast delivery. They offer customized solutions for the specific needs of each business, including international transportation, warehousing, and supply chain management.</p><h3>Why Choose Logistics Transport Companies in Barcelona?</h3><p>Strategic Positioning: Barcelona benefits from an excellent geographical position, facilitating rapid access to markets throughout Europe. This makes the city an ideal starting point for the transport of goods.</p><p>Developed Infrastructure: The city has a modern infrastructure, including seaports, international airports, and well-developed railway networks, which facilitate efficient transportation.</p><p>Diversity of Services: The best logistics transport companies in Barcelona offer a wide range of services, from sea and air transport to warehousing and supply chain management solutions.</p><h3>How to Choose the Best Logistics Transport Company?</h3><p>Choosing the right logistics transport company can be a challenge. Here are some helpful tips:</p><p>Research Available Companies: Check online reviews and compare the services offered by different companies.<br>Check Experience: Choose a company with experience in the field and that understands the specific needs of your business.<br>Request Quotes: Don't hesitate to request price quotes to compare costs and services.</p><h3>Sava Express: The Ideal Partner for Logistics Transport in Barcelona</h3><p>To make the choice easier, we recommend Sava Express – a reliable logistics transport company with extensive experience in the market. They offer complete transport solutions, tailored to your needs, ensuring fast and safe deliveries. Visit www.savaexpress.com for more information.</p><h3>Conclusion</h3><p>Whether you are a small business or a large corporation, choosing a logistics transport company in Barcelona is essential for the success of your operations. By working with professionals like Sava Express, you can benefit from services tailored to your needs and efficient logistics management. Choose wisely and make sure your business is well connected to transportation networks around the world!</p>",
                'image'=>'/backend/images/b3.png',
                'published_date'=>Carbon::now()->format('y-m-d'),
                'created_at'=>Carbon::now()
            ],
             [
                'title'=>'Sava Logistic: Pioneering the Future of Transportation Solutions',
                'author'=>'John',
                'category_id'=>'2',
                'short_description'=>'SAVA Logistics: The Best Choice for Your Logistics Needs in Spain?',

                'long_description'=>"<p>Barcelona, a major commercial and logistics hub in Europe, offers numerous options for logistics transport companies. If you are looking for <strong>logistics transport companies in Barcelona,</strong> you have come to the right place. In this article, we will explore the most relevant transport and logistics services available in this vibrant metropolis.</p><h3>What are Logistics Transport Companies?</h3><p>Logistics transport companies specialize in managing and coordinating the flow of goods and services, ensuring efficient and fast delivery. They offer customized solutions for the specific needs of each business, including international transportation, warehousing, and supply chain management.</p><h3>Why Choose Logistics Transport Companies in Barcelona?</h3><p>Strategic Positioning: Barcelona benefits from an excellent geographical position, facilitating rapid access to markets throughout Europe. This makes the city an ideal starting point for the transport of goods.</p><p>Developed Infrastructure: The city has a modern infrastructure, including seaports, international airports, and well-developed railway networks, which facilitate efficient transportation.</p><p>Diversity of Services: The best logistics transport companies in Barcelona offer a wide range of services, from sea and air transport to warehousing and supply chain management solutions.</p><h3>How to Choose the Best Logistics Transport Company?</h3><p>Choosing the right logistics transport company can be a challenge. Here are some helpful tips:</p><p>Research Available Companies: Check online reviews and compare the services offered by different companies.<br>Check Experience: Choose a company with experience in the field and that understands the specific needs of your business.<br>Request Quotes: Don't hesitate to request price quotes to compare costs and services.</p><h3>Sava Express: The Ideal Partner for Logistics Transport in Barcelona</h3><p>To make the choice easier, we recommend Sava Express – a reliable logistics transport company with extensive experience in the market. They offer complete transport solutions, tailored to your needs, ensuring fast and safe deliveries. Visit www.savaexpress.com for more information.</p><h3>Conclusion</h3><p>Whether you are a small business or a large corporation, choosing a logistics transport company in Barcelona is essential for the success of your operations. By working with professionals like Sava Express, you can benefit from services tailored to your needs and efficient logistics management. Choose wisely and make sure your business is well connected to transportation networks around the world!</p>",
                'image'=>'/backend/images/b2.png',
                'published_date'=>Carbon::now()->format('y-m-d'),
                'created_at'=>Carbon::now()
            ],
        ]);
    }
}
