<?php

namespace Database\Seeders;

use App\Models\Company;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class CompanySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $companies=[
            [
                'sector_id'=>1,
                'logo'=>'backend/images/1.png',
                'created_at'=>now(),
            ],
            [
                'sector_id'=>1,
                'logo'=>'backend/images/2.png',
                'created_at'=>now(),
            ],
            [
                'sector_id'=>1,
                'logo'=>'backend/images/3.png',
                'created_at'=>now(),
            ],
            [
                'sector_id'=>1,
                'logo'=>'backend/images/4.png',
                'created_at'=>now(),
            ],
            [
                'sector_id'=>1,
                'logo'=>'backend/images/5.png',
                'created_at'=>now(),
            ],
            [
                'sector_id'=>1,
                'logo'=>'backend/images/6.png',
                'created_at'=>now(),
            ],
            [
                'sector_id'=>1,
                'logo'=>'backend/images/7.png',
                'created_at'=>now(),
            ],
            [
                'sector_id'=>1,
                'logo'=>'backend/images/8.png',
                'created_at'=>now(),
            ],

            [
                'sector_id'=>2,
                'logo'=>'backend/images/1.png',
                'created_at'=>now(),
            ],
            [
                'sector_id'=>2,
                'logo'=>'backend/images/2.png',
                'created_at'=>now(),
            ],
            [
                'sector_id'=>2,
                'logo'=>'backend/images/3.png',
                'created_at'=>now(),
            ],
            [
                'sector_id'=>2,
                'logo'=>'backend/images/4.png',
                'created_at'=>now(),
            ],
            [
                'sector_id'=>3,
                'logo'=>'backend/images/5.png',
                'created_at'=>now(),
            ],
            [
                'sector_id'=>3,
                'logo'=>'backend/images/6.png',
                'created_at'=>now(),
            ],
            [
                'sector_id'=>3,
                'logo'=>'backend/images/7.png',
                'created_at'=>now(),
            ],
            [
                'sector_id'=>3,
                'logo'=>'backend/images/8.png',
                'created_at'=>now(),
            ],

            [
                'sector_id'=>4,
                'logo'=>'backend/images/1.png',
                'created_at'=>now(),
            ],
            [
                'sector_id'=>4,
                'logo'=>'backend/images/2.png',
                'created_at'=>now(),
            ],
            [
                'sector_id'=>4,
                'logo'=>'backend/images/3.png',
                'created_at'=>now(),
            ],
            [
                'sector_id'=>4,
                'logo'=>'backend/images/4.png',
                'created_at'=>now(),
            ],
            [
                'sector_id'=>5,
                'logo'=>'backend/images/5.png',
                'created_at'=>now(),
            ],
            [
                'sector_id'=>5,
                'logo'=>'backend/images/6.png',
                'created_at'=>now(),
            ],
            [
                'sector_id'=>6,
                'logo'=>'backend/images/7.png',
                'created_at'=>now(),
            ],
            [
                'sector_id'=>6,
                'logo'=>'backend/images/8.png',
                'created_at'=>now(),
            ],
            [
                'sector_id'=>6,
                'logo'=>'backend/images/1.png',
                'created_at'=>now(),
            ],
            [
                'sector_id'=>7,
                'logo'=>'backend/images/2.png',
                'created_at'=>now(),
            ],
            [
                'sector_id'=>7,
                'logo'=>'backend/images/3.png',
                'created_at'=>now(),
            ],
            [
                'sector_id'=>7,
                'logo'=>'backend/images/4.png',
                'created_at'=>now(),
            ],
            [
                'sector_id'=>8,
                'logo'=>'backend/images/5.png',
                'created_at'=>now(),
            ],
            [
                'sector_id'=>8,
                'logo'=>'backend/images/6.png',
                'created_at'=>now(),
            ],
            [
                'sector_id'=>8,
                'logo'=>'backend/images/7.png',
                'created_at'=>now(),
            ],
            [
                'sector_id'=>8,
                'logo'=>'backend/images/8.png',
                'created_at'=>now(),
            ]
        ];

        foreach($companies as $company){
            Company::create($company);
        }
    }
}
