<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CountrySeeder extends Seeder
{
    public function run(): void
    {
        DB::table('countries')->insert([
            [
                'id' => 1,
                'code' => 'AL',
                'name' => 'Albania',
                'full_name' => 'Republic of Albania',
                'iso3' => 'ALB',
            ],
            [
                'id' => 2,
                'code' => 'AN',
                'name' => 'Netherlands Antilles',
                'full_name' => 'Netherlands Antilles',
                'iso3' => 'ANT',
            ],
            [
                'id' => 3,
                'code' => 'AT',
                'name' => 'Austria',
                'full_name' => 'Republic of Austria',
                'iso3' => 'AUT',
            ],
            [
                'id' => 4,
                'code' => 'BA',
                'name' => 'Bosnia and Herzegovina',
                'full_name' => 'Bosnia and Herzegovina',
                'iso3' => 'BIH',
            ],
            [
                'id' => 5,
                'code' => 'BE',
                'name' => 'Belgium',
                'full_name' => 'Kingdom of Belgium',
                'iso3' => 'BEL',
            ],
            [
                'id' => 6,
                'code' => 'BG',
                'name' => 'Bulgaria',
                'full_name' => 'Republic of Bulgaria',
                'iso3' => 'BGR',
            ],
            [
                'id' => 7,
                'code' => 'CH',
                'name' => 'Switzerland',
                'full_name' => 'Swiss Confederation',
                'iso3' => 'CHE',
            ],
            [
                'id' => 8,
                'code' => 'CZ',
                'name' => 'Czech Republic',
                'full_name' => 'Czech Republic',
                'iso3' => 'CZE',
            ],
            [
                'id' => 9,
                'code' => 'DE',
                'name' => 'Germany',
                'full_name' => 'Federal Republic of Germany',
                'iso3' => 'DEU',
            ],
            [
                'id' => 10,
                'code' => 'DK',
                'name' => 'Denmark',
                'full_name' => 'Kingdom of Denmark',
                'iso3' => 'DNK',
            ],
            [
                'id' => 11,
                'code' => 'EE',
                'name' => 'Estonia',
                'full_name' => 'Republic of Estonia',
                'iso3' => 'EST',
            ],
            [
                'id' => 12,
                'code' => 'ES',
                'name' => 'Spain',
                'full_name' => 'Kingdom of Spain',
                'iso3' => 'ESP',
            ],
            [
                'id' => 13,
                'code' => 'FI',
                'name' => 'Finland',
                'full_name' => 'Republic of Finland',
                'iso3' => 'FIN',
            ],
            [
                'id' => 14,
                'code' => 'FR',
                'name' => 'France',
                'full_name' => 'French Republic',
                'iso3' => 'FRA',
            ],
            [
                'id' => 15,
                'code' => 'GB',
                'name' => 'United Kingdom',
                'full_name' => 'United Kingdom of Great Britain & Northern Ireland',
                'iso3' => 'GBR',
            ],
            [
                'id' => 16,
                'code' => 'GE',
                'name' => 'Georgia',
                'full_name' => 'Georgia',
                'iso3' => 'GEO',
            ],
            [
                'id' => 17,
                'code' => 'GL',
                'name' => 'Greenland',
                'full_name' => 'Greenland',
                'iso3' => 'GRL',
            ],
            [
                'id' => 18,
                'code' => 'GR',
                'name' => 'Greece',
                'full_name' => 'Hellenic Republic Greece',
                'iso3' => 'GRC',
            ],
            [
                'id' => 19,
                'code' => 'HR',
                'name' => 'Croatia',
                'full_name' => 'Republic of Croatia',
                'iso3' => 'HRV',
            ],
            [
                'id' => 20,
                'code' => 'HU',
                'name' => 'Hungary',
                'full_name' => 'Republic of Hungary',
                'iso3' => 'HUN',
            ],
            [
                'id' => 21,
                'code' => 'IE',
                'name' => 'Ireland',
                'full_name' => 'Ireland',
                'iso3' => 'IRL',
            ],
            [
                'id' => 22,
                'code' => 'IT',
                'name' => 'Italy',
                'full_name' => 'Italian Republic',
                'iso3' => 'ITA',
            ],
            [
                'id' => 23,
                'code' => 'LT',
                'name' => 'Lithuania',
                'full_name' => 'Republic of Lithuania',
                'iso3' => 'LTU',
            ],
            [
                'id' => 24,
                'code' => 'LU',
                'name' => 'Luxembourg',
                'full_name' => 'Grand Duchy of Luxembourg',
                'iso3' => 'LUX',
            ],
            [
                'id' => 25,
                'code' => 'LV',
                'name' => 'Latvia',
                'full_name' => 'Republic of Latvia',
                'iso3' => 'LVA',
            ],
            [
                'id' => 26,
                'code' => 'MA',
                'name' => 'Morocco',
                'full_name' => 'Kingdom of Morocco',
                'iso3' => 'MAR',
            ],
            [
                'id' => 27,
                'code' => 'MC',
                'name' => 'Monaco',
                'full_name' => 'Principality of Monaco',
                'iso3' => 'MCO',
            ],
            [
                'id' => 28,
                'code' => 'MD',
                'name' => 'Moldova',
                'full_name' => 'Republic of Moldova',
                'iso3' => 'MDA',
            ],
            [
                'id' => 29,
                'code' => 'ME',
                'name' => 'Montenegro',
                'full_name' => 'Republic of Montenegro',
                'iso3' => 'MNE',
            ],
            [
                'id' => 30,
                'code' => 'MK',
                'name' => 'Macedonia',
                'full_name' => 'Republic of Macedonia',
                'iso3' => 'MKD',
            ],
            [
                'id' => 31,
                'code' => 'MT',
                'name' => 'Malta',
                'full_name' => 'Republic of Malta',
                'iso3' => 'MLT',
            ],
            [
                'id' => 32,
                'code' => 'NL',
                'name' => 'Netherlands',
                'full_name' => 'Kingdom of the Netherlands',
                'iso3' => 'NLD',
            ],
            [
                'id' => 33,
                'code' => 'NO',
                'name' => 'Norway',
                'full_name' => 'Kingdom of Norway',
                'iso3' => 'NOR',
            ],
            [
                'id' => 34,
                'code' => 'PL',
                'name' => 'Poland',
                'full_name' => 'Republic of Poland',
                'iso3' => 'POL',
            ],
            [
                'id' => 35,
                'code' => 'PT',
                'name' => 'Portugal',
                'full_name' => 'Portuguese Republic',
                'iso3' => 'PRT',
            ],
            [
                'id' => 36,
                'code' => 'RO',
                'name' => 'Romania',
                'full_name' => 'Romania',
                'iso3' => 'ROU',
            ],
            [
                'id' => 37,
                'code' => 'RS',
                'name' => 'Serbia',
                'full_name' => 'Republic of Serbia',
                'iso3' => 'SRB',
            ],
            [
                'id' => 38,
                'code' => 'RU',
                'name' => 'Russian Federation',
                'full_name' => 'Russian Federation',
                'iso3' => 'RUS',
            ],
            [
                'id' => 39,
                'code' => 'SE',
                'name' => 'Sweden',
                'full_name' => 'Kingdom of Sweden',
                'iso3' => 'SWE',
            ],
            [
                'id' => 40,
                'code' => 'SI',
                'name' => 'Slovenia',
                'full_name' => 'Republic of Slovenia',
                'iso3' => 'SVN',
            ],
            [
                'id' => 41,
                'code' => 'SK',
                'name' => 'Slovakia',
                'full_name' => 'Slovakia (Slovak Republic)',
                'iso3' => 'SVK',
            ],
            [
                'id' => 42,
                'code' => 'SM',
                'name' => 'San Marino',
                'full_name' => 'Republic of San Marino',
                'iso3' => 'SMR',
            ],
            [
                'id' => 43,
                'code' => 'TR',
                'name' => 'Turkey',
                'full_name' => 'Republic of Turkey',
                'iso3' => 'TUR',
            ],
            [
                'id' => 44,
                'code' => 'UA',
                'name' => 'Ukraine',
                'full_name' => 'Ukraine',
                'iso3' => 'UKR',
            ],
            [
                'id' => 45,
                'code' => 'VA',
                'name' => 'Vatican City',
                'full_name' => 'Holy See (Vatican City State)',
                'iso3' => 'VAT',
            ],
            [
                'id' => 46,
                'code' => 'GB',
                'name' => 'GREAT BRITAIN',
                'full_name' => 'GREAT BRITAIN',
                'iso3' => 'VAT',
            ],
        ]);
    }
}
