<?php

namespace Database\Seeders;

use App\Models\TransportRestriction;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class TransportRestrictionSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        TransportRestriction::insert([
                [
                    'country_id'=>2,
                    'description'=>"<h2>🚚 1. Heavy Truck (HGV) Driving Bans</h2><p>&nbsp; &nbsp; &nbsp; Applies to trucks with GVW over 7.5 t (including trailers) across two main restrictions:</p><ul><li><strong>Every Sunday &amp; public holiday</strong><br>– From <strong>00:00 to 22:00</strong>, nationwide</li><li><p><strong>Summer Saturday ban</strong><br>– From <strong>July 1 to August 31</strong>, Saturdays <strong>07:00–20:00</strong> on selected Autobahns and federal routes</p><p>- E.g., A1, A3, A5, A7, A9, A10, A61, A81, A92, A93, A99, and major federal roads like B31, B96.</p></li><li><strong>Penalties:</strong><br>– Drivers face <strong>€120</strong>, companies <strong>€570</strong>. Trucks may be held until the ban ends.</li><li><strong>Exemptions:</strong><br>– Allowed: perishable foods (milk, meat, fish, produce), combined transport (rail/sea), postal services, hazardous materials, emergency, and maintenance vehicles</li></ul><h2>🌍 2. Low-Emission Zones &amp; Emission-based Bans</h2><ul><li>From <strong>Jan 1, 2025</strong>, many cities enforce stricter Low-Emission Zones (LEZs).</li><li>Only <strong>Euro 6 (or newer)</strong> vehicles generally allowed; older diesels (Euro 4/5) face entry bans.</li><li><strong>Fines ~€80</strong> per violation</li></ul><h2>🚗 3. Toll System for Trucks (LKW-Maut)</h2><ul><li>Trucks &gt;7.5 t pay tolls on Autobahns based on distance, emission class, axles: approx. <strong>€0.15/km</strong>.</li><li>Payment via on-board units or manual stations; enforcement via gantries and checks.</li></ul><h3>🛵 4. E-Scooter &amp; Moped Plate Color</h3><ul><li>Starting <strong>March 1, 2025</strong>, e‑scooters and mopeds must display <strong>green insurance plates</strong>—previously blue—to indicate valid liability insurance</li></ul><h2>🚉 5. Deutschlandticket Price</h2><ul><li>The monthly <strong>‘Deutschlandticket’</strong> for nationwide local public transport rose from <strong>€49 to €58</strong> as of January 2025</li><li>Many users still find it good value compared to single-zone passes</li></ul>"
                ],
                [
                    'country_id'=>1,
                    'description'=>"<h2>🚚 1. Heavy Truck (HGV) Driving Bans</h2><p>&nbsp; &nbsp; &nbsp; Applies to trucks with GVW over 7.5 t (including trailers) across two main restrictions:</p><ul><li><strong>Every Sunday &amp; public holiday</strong><br>– From <strong>00:00 to 22:00</strong>, nationwide</li><li><p><strong>Summer Saturday ban</strong><br>– From <strong>July 1 to August 31</strong>, Saturdays <strong>07:00–20:00</strong> on selected Autobahns and federal routes</p><p>- E.g., A1, A3, A5, A7, A9, A10, A61, A81, A92, A93, A99, and major federal roads like B31, B96.</p></li><li><strong>Penalties:</strong><br>– Drivers face <strong>€120</strong>, companies <strong>€570</strong>. Trucks may be held until the ban ends.</li><li><strong>Exemptions:</strong><br>– Allowed: perishable foods (milk, meat, fish, produce), combined transport (rail/sea), postal services, hazardous materials, emergency, and maintenance vehicles</li></ul><h2>🌍 2. Low-Emission Zones &amp; Emission-based Bans</h2><ul><li>From <strong>Jan 1, 2025</strong>, many cities enforce stricter Low-Emission Zones (LEZs).</li><li>Only <strong>Euro 6 (or newer)</strong> vehicles generally allowed; older diesels (Euro 4/5) face entry bans.</li><li><strong>Fines ~€80</strong> per violation</li></ul><h2>🚗 3. Toll System for Trucks (LKW-Maut)</h2><ul><li>Trucks &gt;7.5 t pay tolls on Autobahns based on distance, emission class, axles: approx. <strong>€0.15/km</strong>.</li><li>Payment via on-board units or manual stations; enforcement via gantries and checks.</li></ul><h3>🛵 4. E-Scooter &amp; Moped Plate Color</h3><ul><li>Starting <strong>March 1, 2025</strong>, e‑scooters and mopeds must display <strong>green insurance plates</strong>—previously blue—to indicate valid liability insurance</li></ul><h2>🚉 5. Deutschlandticket Price</h2><ul><li>The monthly <strong>‘Deutschlandticket’</strong> for nationwide local public transport rose from <strong>€49 to €58</strong> as of January 2025</li><li>Many users still find it good value compared to single-zone passes</li></ul>"
                ],
                [
                    'country_id'=>12,
                    'description'=>"<h2>🚚 1. Heavy Truck (HGV) Driving Bans</h2><p>&nbsp; &nbsp; &nbsp; Applies to trucks with GVW over 7.5 t (including trailers) across two main restrictions:</p><ul><li><strong>Every Sunday &amp; public holiday</strong><br>– From <strong>00:00 to 22:00</strong>, nationwide</li><li><p><strong>Summer Saturday ban</strong><br>– From <strong>July 1 to August 31</strong>, Saturdays <strong>07:00–20:00</strong> on selected Autobahns and federal routes</p><p>- E.g., A1, A3, A5, A7, A9, A10, A61, A81, A92, A93, A99, and major federal roads like B31, B96.</p></li><li><strong>Penalties:</strong><br>– Drivers face <strong>€120</strong>, companies <strong>€570</strong>. Trucks may be held until the ban ends.</li><li><strong>Exemptions:</strong><br>– Allowed: perishable foods (milk, meat, fish, produce), combined transport (rail/sea), postal services, hazardous materials, emergency, and maintenance vehicles</li></ul><h2>🌍 2. Low-Emission Zones &amp; Emission-based Bans</h2><ul><li>From <strong>Jan 1, 2025</strong>, many cities enforce stricter Low-Emission Zones (LEZs).</li><li>Only <strong>Euro 6 (or newer)</strong> vehicles generally allowed; older diesels (Euro 4/5) face entry bans.</li><li><strong>Fines ~€80</strong> per violation</li></ul><h2>🚗 3. Toll System for Trucks (LKW-Maut)</h2><ul><li>Trucks &gt;7.5 t pay tolls on Autobahns based on distance, emission class, axles: approx. <strong>€0.15/km</strong>.</li><li>Payment via on-board units or manual stations; enforcement via gantries and checks.</li></ul><h3>🛵 4. E-Scooter &amp; Moped Plate Color</h3><ul><li>Starting <strong>March 1, 2025</strong>, e‑scooters and mopeds must display <strong>green insurance plates</strong>—previously blue—to indicate valid liability insurance</li></ul><h2>🚉 5. Deutschlandticket Price</h2><ul><li>The monthly <strong>‘Deutschlandticket’</strong> for nationwide local public transport rose from <strong>€49 to €58</strong> as of January 2025</li><li>Many users still find it good value compared to single-zone passes</li></ul>"
                ],
                [
                    'country_id'=>3,
                    'description'=>"<h2>🚚 1. Heavy Truck (HGV) Driving Bans</h2><p>&nbsp; &nbsp; &nbsp; Applies to trucks with GVW over 7.5 t (including trailers) across two main restrictions:</p><ul><li><strong>Every Sunday &amp; public holiday</strong><br>– From <strong>00:00 to 22:00</strong>, nationwide</li><li><p><strong>Summer Saturday ban</strong><br>– From <strong>July 1 to August 31</strong>, Saturdays <strong>07:00–20:00</strong> on selected Autobahns and federal routes</p><p>- E.g., A1, A3, A5, A7, A9, A10, A61, A81, A92, A93, A99, and major federal roads like B31, B96.</p></li><li><strong>Penalties:</strong><br>– Drivers face <strong>€120</strong>, companies <strong>€570</strong>. Trucks may be held until the ban ends.</li><li><strong>Exemptions:</strong><br>– Allowed: perishable foods (milk, meat, fish, produce), combined transport (rail/sea), postal services, hazardous materials, emergency, and maintenance vehicles</li></ul><h2>🌍 2. Low-Emission Zones &amp; Emission-based Bans</h2><ul><li>From <strong>Jan 1, 2025</strong>, many cities enforce stricter Low-Emission Zones (LEZs).</li><li>Only <strong>Euro 6 (or newer)</strong> vehicles generally allowed; older diesels (Euro 4/5) face entry bans.</li><li><strong>Fines ~€80</strong> per violation</li></ul><h2>🚗 3. Toll System for Trucks (LKW-Maut)</h2><ul><li>Trucks &gt;7.5 t pay tolls on Autobahns based on distance, emission class, axles: approx. <strong>€0.15/km</strong>.</li><li>Payment via on-board units or manual stations; enforcement via gantries and checks.</li></ul><h3>🛵 4. E-Scooter &amp; Moped Plate Color</h3><ul><li>Starting <strong>March 1, 2025</strong>, e‑scooters and mopeds must display <strong>green insurance plates</strong>—previously blue—to indicate valid liability insurance</li></ul><h2>🚉 5. Deutschlandticket Price</h2><ul><li>The monthly <strong>‘Deutschlandticket’</strong> for nationwide local public transport rose from <strong>€49 to €58</strong> as of January 2025</li><li>Many users still find it good value compared to single-zone passes</li></ul>"
                ],
                [
                    'country_id'=>4,
                    'description'=>"<h2>🚚 1. Heavy Truck (HGV) Driving Bans</h2><p>&nbsp; &nbsp; &nbsp; Applies to trucks with GVW over 7.5 t (including trailers) across two main restrictions:</p><ul><li><strong>Every Sunday &amp; public holiday</strong><br>– From <strong>00:00 to 22:00</strong>, nationwide</li><li><p><strong>Summer Saturday ban</strong><br>– From <strong>July 1 to August 31</strong>, Saturdays <strong>07:00–20:00</strong> on selected Autobahns and federal routes</p><p>- E.g., A1, A3, A5, A7, A9, A10, A61, A81, A92, A93, A99, and major federal roads like B31, B96.</p></li><li><strong>Penalties:</strong><br>– Drivers face <strong>€120</strong>, companies <strong>€570</strong>. Trucks may be held until the ban ends.</li><li><strong>Exemptions:</strong><br>– Allowed: perishable foods (milk, meat, fish, produce), combined transport (rail/sea), postal services, hazardous materials, emergency, and maintenance vehicles</li></ul><h2>🌍 2. Low-Emission Zones &amp; Emission-based Bans</h2><ul><li>From <strong>Jan 1, 2025</strong>, many cities enforce stricter Low-Emission Zones (LEZs).</li><li>Only <strong>Euro 6 (or newer)</strong> vehicles generally allowed; older diesels (Euro 4/5) face entry bans.</li><li><strong>Fines ~€80</strong> per violation</li></ul><h2>🚗 3. Toll System for Trucks (LKW-Maut)</h2><ul><li>Trucks &gt;7.5 t pay tolls on Autobahns based on distance, emission class, axles: approx. <strong>€0.15/km</strong>.</li><li>Payment via on-board units or manual stations; enforcement via gantries and checks.</li></ul><h3>🛵 4. E-Scooter &amp; Moped Plate Color</h3><ul><li>Starting <strong>March 1, 2025</strong>, e‑scooters and mopeds must display <strong>green insurance plates</strong>—previously blue—to indicate valid liability insurance</li></ul><h2>🚉 5. Deutschlandticket Price</h2><ul><li>The monthly <strong>‘Deutschlandticket’</strong> for nationwide local public transport rose from <strong>€49 to €58</strong> as of January 2025</li><li>Many users still find it good value compared to single-zone passes</li></ul>"
                ],
                [
                    'country_id'=>5,
                    'description'=>"<h2>🚚 1. Heavy Truck (HGV) Driving Bans</h2><p>&nbsp; &nbsp; &nbsp; Applies to trucks with GVW over 7.5 t (including trailers) across two main restrictions:</p><ul><li><strong>Every Sunday &amp; public holiday</strong><br>– From <strong>00:00 to 22:00</strong>, nationwide</li><li><p><strong>Summer Saturday ban</strong><br>– From <strong>July 1 to August 31</strong>, Saturdays <strong>07:00–20:00</strong> on selected Autobahns and federal routes</p><p>- E.g., A1, A3, A5, A7, A9, A10, A61, A81, A92, A93, A99, and major federal roads like B31, B96.</p></li><li><strong>Penalties:</strong><br>– Drivers face <strong>€120</strong>, companies <strong>€570</strong>. Trucks may be held until the ban ends.</li><li><strong>Exemptions:</strong><br>– Allowed: perishable foods (milk, meat, fish, produce), combined transport (rail/sea), postal services, hazardous materials, emergency, and maintenance vehicles</li></ul><h2>🌍 2. Low-Emission Zones &amp; Emission-based Bans</h2><ul><li>From <strong>Jan 1, 2025</strong>, many cities enforce stricter Low-Emission Zones (LEZs).</li><li>Only <strong>Euro 6 (or newer)</strong> vehicles generally allowed; older diesels (Euro 4/5) face entry bans.</li><li><strong>Fines ~€80</strong> per violation</li></ul><h2>🚗 3. Toll System for Trucks (LKW-Maut)</h2><ul><li>Trucks &gt;7.5 t pay tolls on Autobahns based on distance, emission class, axles: approx. <strong>€0.15/km</strong>.</li><li>Payment via on-board units or manual stations; enforcement via gantries and checks.</li></ul><h3>🛵 4. E-Scooter &amp; Moped Plate Color</h3><ul><li>Starting <strong>March 1, 2025</strong>, e‑scooters and mopeds must display <strong>green insurance plates</strong>—previously blue—to indicate valid liability insurance</li></ul><h2>🚉 5. Deutschlandticket Price</h2><ul><li>The monthly <strong>‘Deutschlandticket’</strong> for nationwide local public transport rose from <strong>€49 to €58</strong> as of January 2025</li><li>Many users still find it good value compared to single-zone passes</li></ul>"
                ],
            ]);
    }
}
